from typing import Protocol, runtime_checkable, Any
from uuid import UUID
import datetime

@runtime_checkable
class KGClientInterface(Protocol):
    async def upsert_node(self, tenant_id: UUID, label: str, properties: dict) -> str: ...
    async def get_node(self, tenant_id: UUID, node_id: str) -> dict | None: ...
    async def create_relationship(self, tenant_id: UUID, from_id: str, to_id: str, rel_type: str, properties: dict | None = None) -> str: ...
    async def get_related(self, tenant_id: UUID, node_id: str, rel_type: str | None = None, direction: str = "BOTH") -> list[dict]: ...
    async def find_similar_requirements(self, tenant_id: UUID, requirement_text: str, exclude_requirement_id: str | None = None, limit: int = 3, min_similarity: float = 0.2) -> list[dict]: ...
    async def vector_search(self, tenant_id: UUID, embedding: list[float], label: str | None = None, limit: int = 10) -> list[dict]: ...
    async def hybrid_search(self, tenant_id: UUID, query: str, embedding: list[float], label: str | None = None, limit: int = 10) -> list[dict]: ...
    async def delete_node(self, tenant_id: UUID, node_id: str) -> bool: ...
    async def health_check(self) -> bool: ...
